# Generated by Django 4.1.6 on 2023-09-29 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_num',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
